apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Pod
  metadata:
    name: server
    labels:
      app: testapp
  spec:
    containers:
    - name: testapp
      image: webratio/nodejs-http-server
      

